### ISSUE TITLE
..

### ISSUE THREAD

**Issue by Tom88881025** [filplus-bookkeeping/Nandit-Mehra-Lighthouse.Storage#1]

**Comment by nandit123** [comment]
Hi, could you kindly provide responses to the following questions:

1. Have you allocated sufficient tokens for the sector pledge?
2..	Are you involved in data preparation? If so, could you share your prior experience in this role, including any previous applications and corresponding client IDs?
3. How will the data be prepared? Please provide details on the tools and technical approach you plan to use.
4. If you are not responsible for preparing the data, who will be handling it? (Include their name and business details)
5. Has this dataset been stored on Filecoin previously? If yes, what is the reason for storing it again?
6. For optimal storage practices, it is recommended to store large datasets across three or more regions, with at least four different storage provider operators or owners.
7. Please list the Miner IDs, business entities, and locations of the storage providers you plan to collaborate with.

**Comment by Tom88881025** [comment]
Thank you for your review.
1. Yes, the pledged coins are ready.
2. I am a data preparer, mainly using official tools: boost, lotus, or Singularity for data preparation.
3. This dataset has been stored before, but many entries have expired. However, data that is meaningful to humanity is worth being stored repeatedly.
4. The SPs I am currently in communication with are as follows: f03151449 Shenzhen HTY；f01518369 US Mike；f03055029 HK Chris；f03179555 SG YunSD；f03178077 Japan Gong；f03214937 USA Flycloud；f01106668 HK Chris；f03151456 Shenzhen HTY；f01315096 HK Chris；f03179570 SG YunSD；f0870558 HK Chris；f03178144 Japan Gong；f03055005 HK Chris；f03179572 USA Flycloud；f03055018 HK Chris；f01889668 US Mike.

**Comment by nandit123** [comment]
Looks good, as a willing supporter of 512TiB in the first round, please follow the fil-plus rules, and I'll keep an eye out for bot reports to follow.
